### ISSUE TITLE
数据集下载失败

### ISSUE THREAD

**Issue by StearArre** [yeyupiaoling/AudioClassification_Tensorflow#2]
您好，参照文中如下的下载链接下载UrbanSound8K数据集，发现下载经常出现失败且下载速度较低。
麻烦问一下，有没有稳定且速度较高的数据集下载链接或方式呀？
文中数据集下载地址：https://zenodo.org/record/1203745/files/UrbanSound8K.tar.gz。

**Comment by yeyupiaoling** [comment]
@StearArre 你试试用迅雷吧，这个速度很快。
![image](https://user-images.githubusercontent.com/26297768/81266782-f1c5c700-9077-11ea-9c2a-a11e07e1767f.png)

**Comment by StearArre** [comment]
> @StearArre 你试试用迅雷吧，这个速度很快。
> ![image](https://user-images.githubusercontent.com/26297768/81266782-f1c5c700-9077-11ea-9c2a-a11e07e1767f.png)

感谢您回复，我尝试用浏览器、迅雷下载，切换了移动、电信的网络下载此链接都是开始有速度后来速度就变成0了。这几天都在尝试一直是这种情况。
我刚才重新找了一个链接，已经在下载了，再次感谢你哦~
为方便其他遇到跟我相同问题的小伙伴，贴出来链接地址如下：
https://s3.amazonaws.com/pytorch-tutorial-assets/UrbanSound8K.tar.gz

**Comment by yeyupiaoling** [comment]
好的，这个是的确是很快。
