### ISSUE TITLE
tflite转换失败

### ISSUE THREAD

**Issue by thelou1s** [yeyupiaoling/AudioClassification_Tensorflow#3]
你好，我用下载的 h5 模型，用 tensorflow lite convertor 转化为 tflite 模型时报错。命令和 log 如下，请问您知道是什么原因吗？
（用的是tensorflow 2.2.0版本）

命令：
tflite_convert --output_file='/.../models/foo.tflite' --keras_model_file='/.../models/github_yeyupiaoling_resnet50.h5'

log：

"invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
ValueError: None is only supported in the 1st dimension. Tensor 'resnet50v2_input' has invalid shape '[None, 128, None, 1]'.

**Comment by webconfig** [comment]
import tensorflow as tf
saved_model_dir = 'models'
model = tf.saved_model.load(saved_model_dir)
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 128, 128, 1])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
# converter.experimental_new_converter = True
tflite_model = converter.convert()
open('model', 'wb').write(tflite_model)

**Comment by webconfig** [comment]
import tensorflow as tf
saved_model_dir = 'models'
model = tf.saved_model.load(saved_model_dir)
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 128, 128, 1])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()
open('model', 'wb').write(tflite_model)

**Comment by webconfig** [comment]
> 你好，我用下载的 h5 模型，用 tensorflow lite convertor 转化为 tflite 模型时报错。命令和 log 如下，请问您知道是什么原因吗？
> （用的是tensorflow 2.2.0版本）
> 
> 命令：
> tflite_convert --output_file='/.../models/foo.tflite' --keras_model_file='/.../models/github_yeyupiaoling_resnet50.h5'
> 
> log：
> 
> "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
> ValueError: None is only supported in the 1st dimension. Tensor 'resnet50v2_input' has invalid shape '[None, 128, None, 1]'.

import tensorflow as tf
saved_model_dir = 'models'
model = tf.saved_model.load(saved_model_dir)
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 128, 128, 1])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
# converter.experimental_new_converter = True
tflite_model = converter.convert()
open('model', 'wb').write(tflite_model)

**Comment by webconfig** [comment]
> 你好，我用下载的 h5 模型，用 tensorflow lite convertor 转化为 tflite 模型时报错。命令和 log 如下，请问您知道是什么原因吗？
> （用的是tensorflow 2.2.0版本）
> 
> 命令：
> tflite_convert --output_file='/.../models/foo.tflite' --keras_model_file='/.../models/github_yeyupiaoling_resnet50.h5'
> 
> log：
> 
> "invalid shape '{1}'.".format(_get_tensor_name(tensor), shape_list))
> ValueError: None is only supported in the 1st dimension. Tensor 'resnet50v2_input' has invalid shape '[None, 128, None, 1]'.

import tensorflow as tf
saved_model_dir = 'models'
model = tf.saved_model.load(saved_model_dir)
concrete_func = model.signatures[tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY]
concrete_func.inputs[0].set_shape([1, 128, 128, 1])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
tflite_model = converter.convert()
open('model', 'wb').write(tflite_model)
