### ISSUE TITLE
tensorflow 2.0训练过程转换成1.x

### ISSUE THREAD

**Issue by Yang-Changhui** [yeyupiaoling/AudioClassification_Tensorflow#4]
请问下，tensorflow 2.0训练过程如何转换成1.x的呢

**Comment by yeyupiaoling** [comment]
@Yang-Changhui 你可以在tensorflow1.x复现这个模型，还有数据预处理。如果你熟悉tensorflow1.x，主要是参考这来这两个就好。

**Comment by zhangzhaolong-ux** [comment]
请问为什么运行程序时出现：no module named pytest

**Comment by zhangzhaolong-ux** [comment]
我查找了一些原因，但是还是不能解决
